/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CustomerUI;

/**
 *
 * @author Mary Jhezl
 */
public class Agreement extends javax.swing.JFrame {

    /**
     * Creates new form Agreement
     */
    public Agreement() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
        setRentalAgreementText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OKbtn = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        agree = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(21, 25, 28));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 125));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BRB(40 x 40 px) (1).png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGREEMENT");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        OKbtn.setText("OK");
        OKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        agree.setText("I Agree to the Terms ");
        agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agree, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373)
                .addComponent(OKbtn)
                .addGap(55, 55, 55)
                .addComponent(Cancel)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agree, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OKbtn)
                            .addComponent(Cancel))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setRentalAgreementText() {
    String agreementText = """
        RENTAL AGREEMENT TERMS AND CONDITIONS

        1. EQUIPMENT CARE:
           - The rented equipment must be handled with care and kept in proper working condition.
           - Any loss, theft, or damage to the equipment during the rental period is the responsibility of the renter and may result in additional charges ranging up to 10,000.

        2. RETURN POLICY:
           - The equipment must be returned on or before the agreed return date.
           - Late returns will incur a penalty fee of [PENALTY RATE] per day, calculated from the due date.

        3. PAYMENT POLICY:
           - All rental payments are non-refundable once the equipment is picked up or delivered.
           - Any outstanding balance must be settled before the equipment is rented out.

        4. INSPECTION:
           - Equipment condition will be inspected before renting and upon return.
           - Additional fees may apply for any damages discovered after return.

        5. LIABILITY:
           - The renter assumes full responsibility for any injury or damage caused by the use of the equipment during the rental period.
           - The company is not liable for any indirect or direct damages arising from the use of the equipment.

        6. AGREEMENT ACKNOWLEDGMENT:
           - By clicking "I Agree," the renter acknowledges they have read and understood these terms and agree to comply with all conditions.
           - Failure to comply with any of the terms above may result in termination of the rental agreement and/or additional legal action.

        7. OTHER TERMS:
           - The equipment must only be used for its intended purpose.
           - Renting under false information or misrepresentation will void this agreement immediately.

        8. DAMAGE DETAILS:
           - Below is a list of potential damages to the rented equipment and their associated estimated costs:

           Equipment Damage Table:
                           
           Camera:
                      ------------------------------------------------------------------------------------------------------------------------
                      Damage Type                     | Description                                         | Cost
                      ------------------------------------------------------------------------------------------------------------------------
                      Cracked LCD Screen              | The rear screen is broken or unresponsive.        | ₱10,000
                      Sensor Damage                   | Dust, scratches, or dead pixels on the sensor.      | ₱5,000
                      
           
           Lights:
                      ------------------------------------------------------------------------------------------------------------------------
                      Damage Type                        | Description                                         | Cost
                      ------------------------------------------------------------------------------------------------------------------------
                      Broken Bulb or LED Panel        | Bulb or LED stops working due to impact.            | ₱5,000
                      Power Supply Failure              | The power adapter or cord is damaged.             | ₱1,000
                      
                           
           Lenses:
                      ------------------------------------------------------------------------------------------------------------------------
                      Damage Type                         | Description                                         | Cost
                      ------------------------------------------------------------------------------------------------------------------------
                      Focusing Ring Malfunction       | Autofocus or manual focus doesn’t work.           | ₱7,000 
                      Lens Barrel Damage              | Dented or misaligned barrel.                      | ₱5,000 
                           
           
           Sounds (Microphones, Speakers, etc.):
                      ------------------------------------------------------------------------------------------------------------------------
                      Damage Type                         | Description                                     | Cost
                      ------------------------------------------------------------------------------------------------------------------------
                      Broken Microphone Capsule       | No sound pickup or distorted audio.                 | ₱4,000
                      Cable Damage                    | Wires are frayed or cut.                            | ₱2,000
                      
                           
        By proceeding, you confirm that you understand and accept these terms and conditions.
        """;
    
    jTextArea1.setText(agreementText);
    jTextArea1.setCaretPosition(0);
    
    OKbtn.setEnabled(false);
    
    
    }  
    
    
    
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        CustomerMain CusMain = new CustomerMain();
        CusMain.setVisible(true);
        CusMain.pack();
        CusMain.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_CancelActionPerformed

    private void agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeActionPerformed
        OKbtn.setEnabled(agree.isSelected());
    }//GEN-LAST:event_agreeActionPerformed

    private void OKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnActionPerformed
        PaymentMethod pay = new PaymentMethod();
        pay.setVisible(true);
        pay.pack();
        pay.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_OKbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agreement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agreement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agreement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agreement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agreement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton OKbtn;
    private javax.swing.JCheckBox agree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
