
package UI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FullnameFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmailFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PhoneNumberFld = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddressFld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PasswordFld = new javax.swing.JPasswordField();
        SignUpBtn = new javax.swing.JButton();
        OptionsCmbBx = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(470, 20, 300, 48);

        FullnameFld.setForeground(new java.awt.Color(35, 35, 35));
        FullnameFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FullnameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullnameFldActionPerformed(evt);
            }
        });
        jPanel1.add(FullnameFld);
        FullnameFld.setBounds(480, 110, 290, 27);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 150, 120, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fullname:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 80, 120, 16);

        EmailFld.setForeground(new java.awt.Color(35, 35, 35));
        EmailFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EmailFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFldActionPerformed(evt);
            }
        });
        jPanel1.add(EmailFld);
        EmailFld.setBounds(480, 170, 290, 27);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PhoneNumber:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 210, 250, 16);

        PhoneNumberFld.setForeground(new java.awt.Color(35, 35, 35));
        PhoneNumberFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PhoneNumberFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberFldActionPerformed(evt);
            }
        });
        jPanel1.add(PhoneNumberFld);
        PhoneNumberFld.setBounds(480, 230, 290, 27);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 270, 210, 16);

        AddressFld.setForeground(new java.awt.Color(35, 35, 35));
        AddressFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AddressFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFldActionPerformed(evt);
            }
        });
        jPanel1.add(AddressFld);
        AddressFld.setBounds(480, 290, 290, 27);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 330, 160, 16);

        PasswordFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PasswordFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordFld);
        PasswordFld.setBounds(480, 350, 290, 27);

        SignUpBtn.setBackground(new java.awt.Color(51, 51, 51));
        SignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        SignUpBtn.setLabel("SignUp");
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpBtn);
        SignUpBtn.setBounds(480, 390, 70, 20);

        OptionsCmbBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Customer" }));
        OptionsCmbBx.setPreferredSize(new java.awt.Dimension(120, 20));
        OptionsCmbBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsCmbBxActionPerformed(evt);
            }
        });
        jPanel1.add(OptionsCmbBx);
        OptionsCmbBx.setBounds(650, 390, 120, 20);

        jLabel5.setBackground(new java.awt.Color(225, 225, 225));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("I already have an account");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(614, 430, 120, 14);

        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Login");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(740, 430, 45, 18);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Untitled design (49).png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 860, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FullnameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullnameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullnameFldActionPerformed

    private void AddressFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFldActionPerformed

    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        String Fullname, Email, Password, Phone, Address;
        String query, Options;
        String SUrl, SUser, SPass;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:MySQL://localhost:3306/fers", "root", "");
            Statement st = con.createStatement();
            
            if("".equals(FullnameFld.getText())){
                JOptionPane.showMessageDialog(this, "Please enter your full name.", "Missing Information", JOptionPane.WARNING_MESSAGE);
            }else if ("".equals(EmailFld.getText())){
                JOptionPane.showMessageDialog(this, "Please enter your email", "Missing Information", JOptionPane.WARNING_MESSAGE);
                return;
            }else if ("".equals(PasswordFld.getText())){
                JOptionPane.showMessageDialog(this, "Please enter your Password", "Missing Information", JOptionPane.WARNING_MESSAGE);
                return;
            }else if("".equals(AddressFld.getText())){
                JOptionPane.showMessageDialog(this, "Please enter your Address", "Missing Information", JOptionPane.WARNING_MESSAGE);
                return;
            }else if("".equals(PhoneNumberFld.getText())){
                JOptionPane.showMessageDialog(this, "Please enter your Phone Number", "Missing Information", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else{
                Fullname = FullnameFld.getText();
                Email = EmailFld.getText();
                Password = PasswordFld.getText();
                Phone = PhoneNumberFld.getText();
                Address = AddressFld.getText();
                Options = (String) OptionsCmbBx.getSelectedItem();
                
                 int response = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to sign up with the provided details?",
                "Confirm Sign-Up",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
                );
                
                if(response ==  JOptionPane.YES_OPTION){
                    query = "INSERT INTO fers_users(full_name, email, password, user_type, address, phone_number)" +
                            "VALUES('"+Fullname+"' , '"+Email+"' , '"+Password+"' , '"+Options+"' , '"+Address+"' , '"+Phone+"')";

                    st.execute(query);
                    FullnameFld.setText("");
                    EmailFld.setText("");
                    PasswordFld.setText("");
                    PhoneNumberFld.setText("");
                    AddressFld.setText("");
                    OptionsCmbBx.setSelectedItem(0);

                    showMessageDialog(null, "Account added Successfully!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage(), "Error Message", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SignUpBtnActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login log = new Login();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void OptionsCmbBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsCmbBxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionsCmbBxActionPerformed

    private void PasswordFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFldActionPerformed

    private void EmailFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFldActionPerformed

    private void PhoneNumberFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberFldActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressFld;
    private javax.swing.JTextField EmailFld;
    private javax.swing.JTextField FullnameFld;
    private javax.swing.JComboBox<String> OptionsCmbBx;
    private javax.swing.JPasswordField PasswordFld;
    private javax.swing.JTextField PhoneNumberFld;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
