/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminUI;

import UI.Login;

/**
 *
 * @author dave
 */
public class AdminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainMenu
     */
    public AdminMainMenu() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rentalRecBtn = new javax.swing.JButton();
        updatePayBtn = new javax.swing.JButton();
        rentalstatusBtn = new javax.swing.JButton();
        payHistoryBtn = new javax.swing.JButton();
        EquipmentsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LogOutBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(null);

        rentalRecBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rentalRecBtn.setText("Rental Record");
        rentalRecBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalRecBtnActionPerformed(evt);
            }
        });
        jPanel1.add(rentalRecBtn);
        rentalRecBtn.setBounds(570, 400, 280, 70);

        updatePayBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        updatePayBtn.setText("Update Payment");
        updatePayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatePayBtn);
        updatePayBtn.setBounds(570, 240, 280, 70);

        rentalstatusBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rentalstatusBtn.setText("Update Rental Status");
        rentalstatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalstatusBtnActionPerformed(evt);
            }
        });
        jPanel1.add(rentalstatusBtn);
        rentalstatusBtn.setBounds(570, 320, 280, 70);

        payHistoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        payHistoryBtn.setText("View Payment History");
        payHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payHistoryBtnActionPerformed(evt);
            }
        });
        jPanel1.add(payHistoryBtn);
        payHistoryBtn.setBounds(570, 480, 280, 70);

        EquipmentsBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EquipmentsBtn.setText("Equipments");
        EquipmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmentsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EquipmentsBtn);
        EquipmentsBtn.setBounds(570, 160, 280, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/film 3 blur (1000 x 490 px).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 110, 1000, 490);

        jPanel3.setBackground(new java.awt.Color(21, 25, 28));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(599, 125));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BRBLogo.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 150, 110));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome Back, Admin!");
        jLabel6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel6ComponentMoved(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 60));

        LogOutBtn1.setText("Log Out");
        LogOutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(LogOutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 110);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtn1ActionPerformed
        Login MainMenu = new Login();
        MainMenu.setVisible(true);
        MainMenu.pack();
        MainMenu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LogOutBtn1ActionPerformed

    private void EquipmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmentsBtnActionPerformed
        CRUDequipment eq = new CRUDequipment();
        eq.setVisible(true);
        eq.pack();
        eq.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_EquipmentsBtnActionPerformed

    private void rentalstatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalstatusBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentalstatusBtnActionPerformed

    private void updatePayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePayBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePayBtnActionPerformed

    private void rentalRecBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalRecBtnActionPerformed
        RentalRecord rent = new RentalRecord();
        rent.setVisible(true);
        rent.pack();
        rent.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_rentalRecBtnActionPerformed

    private void payHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payHistoryBtnActionPerformed
        ViewPaymentHistory pay = new ViewPaymentHistory();
        pay.setVisible(true);
        pay.pack();
        pay.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_payHistoryBtnActionPerformed

    private void jLabel6ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel6ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6ComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EquipmentsBtn;
    private javax.swing.JButton LogOutBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton payHistoryBtn;
    private javax.swing.JButton rentalRecBtn;
    private javax.swing.JButton rentalstatusBtn;
    private javax.swing.JButton updatePayBtn;
    // End of variables declaration//GEN-END:variables
}
