/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminUI;

import Database.DatabaseConn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author dave
 */
public class UpdateLogs extends javax.swing.JFrame {

    /**
     * Creates new form UpdateLogs
     */
    public UpdateLogs() {
        initComponents();
        loadUpdateLogs(updateTbl);
    }

private void loadUpdateLogs(JTable updateLogsTable) { 
    String query = "SELECT item_id, category, brand, model_num, rent_price, quantity, status, updated_at FROM update_logs";    
    
    try (Connection con = DatabaseConn.connect(); 
         PreparedStatement pst = con.prepareStatement(query); 
         ResultSet rs = pst.executeQuery()) {
       
        ResultSetMetaData metaData = rs.getMetaData();
        int columnCount = metaData.getColumnCount();
        DefaultTableModel tableModel = new DefaultTableModel();
        for (int i = 1; i <= columnCount; i++) {
            tableModel.addColumn(metaData.getColumnName(i));
        }

        while (rs.next()) {
            Object[] rowData = new Object[columnCount];
            for (int i = 1; i <= columnCount; i++) {
                rowData[i - 1] = rs.getObject(i);
            }
            tableModel.addRow(rowData);
        }

        updateLogsTable.setModel(tableModel);

        updateLogsTable.getColumnModel().getColumn(0).setPreferredWidth(40);  
        updateLogsTable.getColumnModel().getColumn(1).setPreferredWidth(90); 
        updateLogsTable.getColumnModel().getColumn(2).setPreferredWidth(100); 
        updateLogsTable.getColumnModel().getColumn(3).setPreferredWidth(90);
        updateLogsTable.getColumnModel().getColumn(4).setPreferredWidth(90);
        updateLogsTable.getColumnModel().getColumn(5).setPreferredWidth(80);  
        updateLogsTable.getColumnModel().getColumn(6).setPreferredWidth(100); 
        updateLogsTable.getColumnModel().getColumn(7).setPreferredWidth(150);

        for (int i = 0; i < columnCount; i++) {
            updateLogsTable.getColumnModel().getColumn(i).setCellEditor(null);
        }
        updateLogsTable.getTableHeader().setReorderingAllowed(false);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SearchFld = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(21, 25, 28));
        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BRBLogo.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 147, 90);

        SearchFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFldActionPerformed(evt);
            }
        });
        jPanel3.add(SearchFld);
        SearchFld.setBounds(202, 40, 250, 28);

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel3.add(SearchBtn);
        SearchBtn.setBounds(460, 40, 73, 28);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel3.add(BackBtn);
        BackBtn.setBounds(593, 40, 60, 28);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 700, 90);

        jPanel2.setLayout(new java.awt.BorderLayout());

        updateTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category", "Brand", "Model Number", "Rent Price", "Quantity", "Status", "Updated at"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(updateTbl);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 90, 700, 310);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        AdminMainMenu AmM = new AdminMainMenu();
        AmM.setVisible(true);
        AmM.pack();
        AmM.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        DefaultTableModel ob = (DefaultTableModel) updateTbl.getModel();
        TableRowSorter <DefaultTableModel> obj = new TableRowSorter<>(ob);
        updateTbl.setRowSorter(obj);
        
        String searchKeyword = SearchFld.getText().trim();
        if (!searchKeyword.isEmpty()) {
        obj.setRowFilter(RowFilter.regexFilter("(?i)" + searchKeyword)); 
        } else {
        obj.setRowFilter(null);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void SearchFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFldActionPerformed
        SearchFldActionPerformed(null);
    }//GEN-LAST:event_SearchFldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchFld;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable updateTbl;
    // End of variables declaration//GEN-END:variables
}
