package AdminUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Mary Jhezl
 */
public class UpdateEquipment extends javax.swing.JFrame {

    /**
     * Creates new form UpdateEquipment
     */
    public UpdateEquipment() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtUpdateEquipment = new javax.swing.JLabel();
        equipmentName = new javax.swing.JTextField();
        txtequipmentName = new javax.swing.JLabel();
        txtequipmentType = new javax.swing.JLabel();
        equipmentType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        txtrentPrice = new javax.swing.JLabel();
        rentPrice = new javax.swing.JTextField();
        txtAvailability = new javax.swing.JLabel();
        availability = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 40, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 50));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mary Jhezl\\Downloads\\EQUIPMENTS RENTAL (100 x 100 px) (140 x 140 px) (2).png")); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel9.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 110));

        jPanel4.setLayout(null);
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 389, -1, -1));

        txtUpdateEquipment.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtUpdateEquipment.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdateEquipment.setText("UPDATE EQUIPMENT");
        jPanel1.add(txtUpdateEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        equipmentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentNameActionPerformed(evt);
            }
        });
        jPanel1.add(equipmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 390, -1));

        txtequipmentName.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txtequipmentName.setForeground(new java.awt.Color(255, 255, 255));
        txtequipmentName.setText("Equipment Name :");
        jPanel1.add(txtequipmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        txtequipmentType.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txtequipmentType.setForeground(new java.awt.Color(255, 255, 255));
        txtequipmentType.setText("Equipment Type :");
        jPanel1.add(txtequipmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        jPanel1.add(equipmentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 390, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 390, 50));

        txtrentPrice.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txtrentPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtrentPrice.setText("Rent Price :");
        jPanel1.add(txtrentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, 28));
        jPanel1.add(rentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 390, -1));

        txtAvailability.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txtAvailability.setForeground(new java.awt.Color(255, 255, 255));
        txtAvailability.setText("Availability :");
        jPanel1.add(txtAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, 28));
        jPanel1.add(availability, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 390, -1));

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipmentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentNameActionPerformed

    }//GEN-LAST:event_equipmentNameActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered

    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        AdminMainMenu AdMain = new AdminMainMenu();
        AdMain.pack();
        AdMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEquipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availability;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField description;
    private javax.swing.JTextField equipmentName;
    private javax.swing.JTextField equipmentType;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField rentPrice;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel txtAvailability;
    private javax.swing.JLabel txtUpdateEquipment;
    private javax.swing.JLabel txtequipmentName;
    private javax.swing.JLabel txtequipmentType;
    private javax.swing.JLabel txtrentPrice;
    // End of variables declaration//GEN-END:variables
}
